package com.xkcd.comicreader.util;

import java.util.ArrayList;

public class Constant {

    //  http://xkcd.com/{comicId}/info.0.json -> URL_HEAD+Comic.getNum()+URL_TAIL
    //  http://xkcd.com/info.0.json -> URL_HEAD+URL_TAIL

    public static final String URL_HEAD = "https://xkcd.com/";
    public static final String URL_TAIL = "/info.0.json";
    public static final String UPDATE_URL = URL_HEAD+URL_TAIL;
    public static final String SHOP_URL = "https://store.xkcd.com/";

    public static String DB_NAME = "comic.db";
    public static String TABLE_FAVOR = "favor";
    public static Integer DB_VERSION = 1;

    //create table test (id integer primary key autoincrement, json text);
    /**
     * sqlite db table, also could add alt and other useful feature later
     */
    public static final String CREATE_TABLE = "(id integer primary key, " +
                                        "img text, " +
                                        "title text, " +
                                        "status integer)";  // status: 1 means normal status, for all data store (have read); 2 means haven't read; 3 means favor comic
                                                            // when refresh, the data should add status with 2 (haven't read)
                                                            // when add to favor, status should be changed to 1
                                                            // when the comic have been read change it into 1

    public static final Integer INIT_STATUS = 1;
    public static final Integer UNREAD_STATUS = 2;
    public static final Integer FAVOR_STATUS = 3;

    // suppose this is the data get from net
    public static final ArrayList<String> NEW_DATA =
            new ArrayList<String>(){{
                add("{\"month\": \"7\", \"num\": 2172, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"Lunar Cycles\", \"transcript\": \"\", \"alt\": \"The Antikythera mechanism had a whole set of gears specifically to track the cyclic popularity of skinny jeans and low-rise waists.\", \"img\": \"https://imgs.xkcd.com/comics/lunar_cycles.png\", \"title\": \"Lunar Cycles\", \"day\": \"5\"}");
                add("{\"month\": \"7\", \"num\": 2171, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"Shadow Biosphere\", \"transcript\": \"\", \"alt\": \"The typical Shadow Biology Department is housed in a building coated in a thin layer of desert varnish which renders it invisible to normal-world university staff.\", \"img\": \"https://imgs.xkcd.com/comics/shadow_biosphere.png\", \"title\": \"Shadow Biosphere\", \"day\": \"3\"}");
                add("{\"month\": \"7\", \"num\": 2170, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"Coordinate Precision\", \"transcript\": \"\", \"alt\": \"40 digits: You are optimistic about our understanding of the nature of distance itself.\", \"img\": \"https://imgs.xkcd.com/comics/coordinate_precision.png\", \"title\": \"Coordinate Precision\", \"day\": \"1\"}");
                add("{\"month\": \"6\", \"num\": 2169, \"link\": \" [AT THE JULY 28TH MEETING][tab] \\\"Cancel the meeting! Our cover is blown.\\\"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"Predictive Models\", \"transcript\": \"\", \"alt\": \"WE WILL ARREST THE REVOLUTION MEMBERS\", \"img\": \"https://imgs.xkcd.com/comics/predictive_models.png\", \"title\": \"Predictive Models\", \"day\": \"28\"}");
                add("{\"month\": \"6\", \"num\": 2168, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"Reading in the Original\", \"transcript\": \"\", \"alt\": \"The articles are much shorter, but I assume that's because this version predates the merger with the Hawaiian text that created the modern Hawaiian-Greek hybrid wiki-pedia.\", \"img\": \"https://imgs.xkcd.com/comics/reading_in_the_original.png\", \"title\": \"Reading in the Original\", \"day\": \"26\"}");
                add("{\"month\": \"6\", \"num\": 2167, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"Motivated Reasoning Olympics\", \"transcript\": \"\", \"alt\": \"[later] I can't believe how bad corruption has become, especially given that our league split off from the statewide one a month ago SPECIFICALLY to protest this kind of flagrantly biased judging.\", \"img\": \"https://imgs.xkcd.com/comics/motivated_reasoning_olympics.png\", \"title\": \"Motivated Reasoning Olympics\", \"day\": \"24\"}");
                }};


    // use for init data in sqlite

    public static final ArrayList<String> INIT_DATA = new ArrayList<String>(){{
        add("{\"month\": \"4\", \"num\": 2140, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"Reinvent the Wheel\", \"transcript\": \"\", \"alt\": \"Right now it's a bicycle wheel, so we've had to move to lighter vehicles, but the reduced overhead is worth it. There was one week when a wheel of cheese got dangerously close to the first page, though.\", \"img\": \"https://imgs.xkcd.com/comics/reinvent_the_wheel.png\", \"title\": \"Reinvent the Wheel\", \"day\": \"22\"}");
        add("{\"month\": \"4\", \"num\": 2141, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"UI vs UX\", \"transcript\": \"\", \"alt\": \"U[unprintable glyph]: The elements a higher power uses to bend that moral arc. U[even more unprintable glyph]: The higher power's overall experience bending that moral arc.\", \"img\": \"https://imgs.xkcd.com/comics/ui_vs_ux.png\", \"title\": \"UI vs UX\", \"day\": \"24\"}");
        add("{\"month\": \"4\", \"num\": 2142, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"Dangerous Fields\", \"transcript\": \"\", \"alt\": \"Eventually, every epidemiologist becomes another statistic, a dedication to record-keeping which their colleagues sincerely appreciate.\", \"img\": \"https://imgs.xkcd.com/comics/dangerous_fields.png\", \"title\": \"Dangerous Fields\", \"day\": \"26\"}");
        add("{\"month\": \"4\", \"num\": 2143, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"Disk Usage\", \"transcript\": \"\", \"alt\": \"Menu -> Manage -> [Optimize space usage, Encrypt disk usage report, Convert photos to text-only, Delete temporary files, Delete permanent files, Delete all files currently in use, Optimize menu options, Download cloud, Optimize cloud , Upload unused space to cloud]\", \"img\": \"https://imgs.xkcd.com/comics/disk_usage.png\", \"title\": \"Disk Usage\", \"day\": \"29\"}");
        add("{\"month\": \"5\", \"num\": 2144, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"Adjusting a Chair\", \"transcript\": \"\", \"alt\": \"When I was looking at the box, I should have thought more about what \\\"360 degrees of freedom\\\" meant.\", \"img\": \"https://imgs.xkcd.com/comics/adjusting_a_chair.png\", \"title\": \"Adjusting a Chair\", \"day\": \"1\"}");
        add("{\"month\": \"5\", \"num\": 2145, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"Heists And Escapes\", \"transcript\": \"\", \"alt\": \"The interactive experience is built on a single theological framework that unites Dante, George R. R. Martin, every major heist movie, and Erin Gloria Ryan's \\\"Kevin is dead\\\" Home Alone theory.\", \"img\": \"https://imgs.xkcd.com/comics/heists_and_escapes.png\", \"title\": \"Heists And Escapes\", \"day\": \"3\"}");
        add("{\"month\": \"5\", \"num\": 2146, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"Waiting for the But\", \"transcript\": \"\", \"alt\": \"Listen, I'm not a fan of the Spanish Inquisition OR predatory multi-level marketing schemes...\", \"img\": \"https://imgs.xkcd.com/comics/waiting_for_the_but.png\", \"title\": \"Waiting for the But\", \"day\": \"6\"}");
        add("{\"month\": \"5\", \"num\": 2147, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"Appendicitis\", \"transcript\": \"\", \"alt\": \"Fortunately, after a brief skirmish, I seem to have gained the upper hand in the battle against my internal organs, at least until they learn to read and find out the mean stuff I've said about them.\", \"img\": \"https://imgs.xkcd.com/comics/appendicitis.png\", \"title\": \"Appendicitis\", \"day\": \"8\"}");
        add("{\"month\": \"5\", \"num\": 2148, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"Cubesat Launch\", \"transcript\": \"\", \"alt\": \"Luckily, the damages were partly offset by the prize money we got from accidentally winning the nearby water skiing championship tournament.\", \"img\": \"https://imgs.xkcd.com/comics/cubesat_launch.png\", \"title\": \"Cubesat Launch\", \"day\": \"10\"}");
        add("{\"month\": \"5\", \"num\": 2149, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"Alternate Histories\", \"transcript\": \"\", \"alt\": \"\\\"So their universe wouldn't have the iconic photo of a screaming Truman being hoisted aloft by the newspaper-printing machinery...\\\"\", \"img\": \"https://imgs.xkcd.com/comics/alternate_histories.png\", \"title\": \"Alternate Histories\", \"day\": \"13\"}");
    }};

    public static final ArrayList<String> MORE_DATA =
            new ArrayList<String>(){{
                add("{\"month\": \"5\", \"num\": 2150, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"XKeyboarCD\", \"transcript\": \"\", \"alt\": \"The key caps use LCD displays for all the vowels, so they can automatically adjust over the years to reflect ongoing vowel shifts while allowing you to keep typing phonetically.\", \"img\": \"https://imgs.xkcd.com/comics/xkeyboarcd.png\", \"title\": \"XKeyboarCD\", \"day\": \"15\"}");
                add("{\"month\": \"5\", \"num\": 2151, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"A/B\", \"transcript\": \"\", \"alt\": \"We wrote our site in Linear A rather than Aksara Kawi because browser testing showed that Crete script rendered faster than Java script.\", \"img\": \"https://imgs.xkcd.com/comics/a_b.png\", \"title\": \"A/B\", \"day\": \"17\"}");
                add("{\"month\": \"5\", \"num\": 2152, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"Westerns\", \"transcript\": \"\", \"alt\": \"Sitting here idly trying to figure out how the population of the Old West in the late 1800s compares to the number of Red Dead Redemption 2 players.\", \"img\": \"https://imgs.xkcd.com/comics/westerns.png\", \"title\": \"Westerns\", \"day\": \"20\"}");
                add("{\"month\": \"5\", \"num\": 2153, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"Effects of High Altitude\", \"transcript\": \"\", \"alt\": \"If she'd lived in Flagstaff (elevation 6,903 feet), Cruella de Vil would only have needed 89 dalmatians for her coat.\", \"img\": \"https://imgs.xkcd.com/comics/effects_of_high_altitude.png\", \"title\": \"Effects of High Altitude\", \"day\": \"22\"}");
                add("{\"month\": \"5\", \"num\": 2154, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"Motivation\", \"transcript\": \"\", \"alt\": \"What's even worse is, a month ago they transferred me to work on the game I was already playing, and suddenly I found myself procrastinating by playing the one I'd been assigned before. It's possible they're onto me and this is all part of the plan.\", \"img\": \"https://imgs.xkcd.com/comics/motivation.png\", \"title\": \"Motivation\", \"day\": \"24\"}");
                add("{\"month\": \"5\", \"num\": 2155, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"Swimming\", \"transcript\": \"\", \"alt\": \"\\\"You don't know how high above you the sky goes, but you're not freaking out about that.\\\" \\\"Well, NOW I am!\\\"\", \"img\": \"https://imgs.xkcd.com/comics/swimming.png\", \"title\": \"Swimming\", \"day\": \"27\"}");
                add("{\"month\": \"5\", \"num\": 2156, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"Ufo\", \"transcript\": \"\", \"alt\": \"\\\"It's a little low for a weather balloon; it might be some other kind.\\\" \\\"Yeah. Besides, I know I'm the alien conspiracy guy, but come on--the idea that the government would care about hiding something so mundane as atmospheric temperature measurement is too ridiculous even for me.\\\"\", \"img\": \"https://imgs.xkcd.com/comics/ufo.png\", \"title\": \"Ufo\", \"day\": \"29\"}");
                add("{\"month\": \"5\", \"num\": 2157, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"Diploma Legal Notes\", \"transcript\": \"\", \"alt\": \"If you're planning to challenge the royal family, you should probably wait 6-8 weeks, since a number of the younger ones have diplomas and Kate was actually on the varsity lightsaber team at St Andrews.\", \"img\": \"https://imgs.xkcd.com/comics/diploma_legal_notes.png\", \"title\": \"Diploma Legal Notes\", \"day\": \"31\"}");
                add("{\"month\": \"6\", \"num\": 2158, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"Qualifiers\", \"transcript\": \"\", \"alt\": \"[20 minutes later] \\\", hi.\\\"\", \"img\": \"https://imgs.xkcd.com/comics/qualifiers.png\", \"title\": \"Qualifiers\", \"day\": \"3\"}");
                add("{\"month\": \"6\", \"num\": 2159, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"Comments\", \"transcript\": \"\", \"alt\": \"NPR encourages you to add comments to their stories using the page inspector in your browser's developer tools. Note: Your comments are visible only to you, and will be lost when you refresh the page.\", \"img\": \"https://imgs.xkcd.com/comics/comments.png\", \"title\": \"Comments\", \"day\": \"5\"}");
                add("{\"month\": \"6\", \"num\": 2160, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"Ken Burns Theory\", \"transcript\": \"\", \"alt\": \"Some of the KBCU ancillary works try a little too hard to tie everything together. Doris Kearns Goodwin, the sports journalist featured in \\\"Baseball,\\\" was somehow ALSO a famous historian who wrote bestselling biographies of Lincoln AND Johnson? Unrealistic.\", \"img\": \"https://imgs.xkcd.com/comics/ken_burns_theory.png\", \"title\": \"Ken Burns Theory\", \"day\": \"7\"}");
                add("{\"month\": \"6\", \"num\": 2161, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"An Apple a Day\", \"transcript\": \"\", \"alt\": \"Even the powerful, tart Granny Smith cultivar is proving ineffective against new Gran-negative doctors.\", \"img\": \"https://imgs.xkcd.com/comics/an_apple_a_day.png\", \"title\": \"An Apple a Day\", \"day\": \"10\"}");
                add("{\"month\": \"6\", \"num\": 2162, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"Literary Opinions\", \"transcript\": \"\", \"alt\": \"If I really focus, I can distinguish between John Steinbeck and John Updike, or between Gore Vidal and Vidal Sassoon, but not both at once.\", \"img\": \"https://imgs.xkcd.com/comics/literary_opinions.png\", \"title\": \"Literary Opinions\", \"day\": \"12\"}");
                add("{\"month\": \"6\", \"num\": 2163, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"Chernobyl\", \"transcript\": \"\", \"alt\": \"You know when you can't hear your speakers, and you keep turning various volume controls up higher and higher in confusion, and then someone hits the mute button and there's a deafening blast of sound? That's basically what happened at Chernobyl.\", \"img\": \"https://imgs.xkcd.com/comics/chernobyl.png\", \"title\": \"Chernobyl\", \"day\": \"14\"}");
                add("{\"month\": \"6\", \"num\": 2164, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"Glacier\", \"transcript\": \"\", \"alt\": \"The Norwegian adaptation of The Sword in the Stone takes things in a weird direction.\", \"img\": \"https://imgs.xkcd.com/comics/glacier.png\", \"title\": \"Glacier\", \"day\": \"17\"}");
                add("{\"month\": \"6\", \"num\": 2165, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"Millennials\", \"transcript\": \"\", \"alt\": \"Ironically, I've been having these same arguments for at least a decade now. I thought we would have moved on by now, but somehow the snide complaints about millennials continue.\", \"img\": \"https://imgs.xkcd.com/comics/millennials.png\", \"title\": \"Millennials\", \"day\": \"19\"}");
                add("{\"month\": \"6\", \"num\": 2166, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"Stack\", \"transcript\": \"\", \"alt\": \"Gotta feel kind of bad for nation-state hackers who spend years implanting and cultivating some hardware exploit, only to discover the entire target database is already exposed to anyone with a web browser.\", \"img\": \"https://imgs.xkcd.com/comics/stack.png\", \"title\": \"Stack\", \"day\": \"21\"}");
            }};

    public static final ArrayList<String> OLD_DATA =
            new ArrayList<String>(){{
                add("{\"month\": \"2\", \"num\": 2115, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"Plutonium\", \"transcript\": \"\", \"alt\": \"It's like someone briefly joined the team running the universe, introduced their idea for a cool mechanic, then left, and now everyone is stuck pretending that this wildly unbalanced dynamic makes sense.\", \"img\": \"https://imgs.xkcd.com/comics/plutonium.png\", \"title\": \"Plutonium\", \"day\": \"22\"}");
                add("{\"month\": \"2\", \"num\": 2116, \"link\": \"https://twitter.com/openelex/status/853977391747801088\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \".NORM Normal File Format\", \"transcript\": \"\", \"alt\": \"At some point, compression becomes an  aesthetic design choice. Luckily, SVG is a really flexible format, so there's no reason it can't support vector JPEG artifacts.\", \"img\": \"https://imgs.xkcd.com/comics/norm_normal_file_format.png\", \"title\": \".NORM Normal File Format\", \"day\": \"25\"}");
                add("{\"month\": \"2\", \"num\": 2117, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"Differentiation and Integration\", \"transcript\": \"\", \"alt\": \"\\\"Symbolic integration\\\" is when you theatrically go through the motions of finding integrals, but the actual result you get doesn't matter because it's purely symbolic.\", \"img\": \"https://imgs.xkcd.com/comics/differentiation_and_integration.png\", \"title\": \"Differentiation and Integration\", \"day\": \"27\"}");
                add("{\"month\": \"3\", \"num\": 2118, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"Normal Distribution\", \"transcript\": \"\", \"alt\": \"It's the NORMAL distribution, not the TANGENT distribution.\", \"img\": \"https://imgs.xkcd.com/comics/normal_distribution.png\", \"title\": \"Normal Distribution\", \"day\": \"1\"}");
                add("{\"month\": \"3\", \"num\": 2119, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"Video Orientation\", \"transcript\": \"\", \"alt\": \"CIRCULAR VIDEO - PROS: Solves aspect ratio problem. CONS: Never trust anyone who talks to you from inside a circle.\", \"img\": \"https://imgs.xkcd.com/comics/video_orientation.png\", \"title\": \"Video Orientation\", \"day\": \"4\"}");
                add("{\"month\": \"3\", \"num\": 2120, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"Brain Hemispheres\", \"transcript\": \"\", \"alt\": \"Neurologically speaking, the LEFT hand is actually the one at the end of the RIGHT arm.\", \"img\": \"https://imgs.xkcd.com/comics/brain_hemispheres.png\", \"title\": \"Brain Hemispheres\", \"day\": \"6\"}");
                add("{\"month\": \"3\", \"num\": 2121, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"Light Pollution\", \"transcript\": \"\", \"alt\": \"It's so sad how almost no one alive today can remember seeing the galactic rainbow, the insanity nebula, or the skull and glowing eyes of the Destroyer of Sagittarius.\", \"img\": \"https://imgs.xkcd.com/comics/light_pollution.png\", \"title\": \"Light Pollution\", \"day\": \"8\"}");
                add("{\"month\": \"3\", \"num\": 2122, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"Size Venn Diagram\", \"transcript\": \"\", \"alt\": \"Terms I'm going to start using: The Large Dipper, great potatoes, the Big Hadron Collider, and Large Orphan Annie.\", \"img\": \"https://imgs.xkcd.com/comics/size_venn_diagram.png\", \"title\": \"Size Venn Diagram\", \"day\": \"11\"}");
                add("{\"month\": \"3\", \"num\": 2123, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"Meta Collecting\", \"transcript\": \"\", \"alt\": \"I'm trying to get the page locked because some jerk keeps adding \\\"Yachts\\\".\", \"img\": \"https://imgs.xkcd.com/comics/meta_collecting.png\", \"title\": \"Meta Collecting\", \"day\": \"13\"}");
                add("{\"month\": \"3\", \"num\": 2124, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"Space Mission Hearing\", \"transcript\": \"\", \"alt\": \"Our grant application contains one of those little greeting card speakers that plays spaceship noises when you open it.\", \"img\": \"https://imgs.xkcd.com/comics/space_mission_hearing.png\", \"title\": \"Space Mission Hearing\", \"day\": \"15\"}");
                add("{\"month\": \"3\", \"num\": 2125, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"Luna 2\", \"transcript\": \"\", \"alt\": \"The flags were probably vaporized on impact, because we launched it before we had finished figuring out how to land. That makes sense from an engineering standpoint, but also feels like a metaphor.\", \"img\": \"https://imgs.xkcd.com/comics/luna_2.png\", \"title\": \"Luna 2\", \"day\": \"18\"}");
                add("{\"month\": \"3\", \"num\": 2126, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"Google Trends Maps\", \"transcript\": \"\", \"alt\": \"It's early 2020. The entire country is gripped with Marco Rubio fever except for Alaska, which is freaking out. You're frantically studying up on etiquette and/or sexting.\", \"img\": \"https://imgs.xkcd.com/comics/google_trends_maps.png\", \"title\": \"Google Trends Maps\", \"day\": \"20\"}");
                add("{\"month\": \"3\", \"num\": 2127, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"Panama Canal\", \"transcript\": \"\", \"alt\": \"Once they selected the other proposal, we could have kept shopping ours around, but we would had to modify it include an aqueduct over their canal, which would be totally unreasonable.\", \"img\": \"https://imgs.xkcd.com/comics/panama_canal.png\", \"title\": \"Panama Canal\", \"day\": \"22\"}");
                add("{\"month\": \"3\", \"num\": 2128, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"New Robot\", \"transcript\": \"\", \"alt\": \"\\\"Some worry that we'll soon have a surplus of search and rescue robots, compared to the number of actual people in situations requiring search and rescue. That's where our other robot project comes in...\\\"\", \"img\": \"https://imgs.xkcd.com/comics/new_robot.png\", \"title\": \"New Robot\", \"day\": \"25\"}");
                add("{\"month\": \"3\", \"num\": 2129, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"1921 Fact Checker\", \"transcript\": \"\", \"alt\": \"POLITIFACT SAYS: MOSTLY WHATEVER\", \"img\": \"https://imgs.xkcd.com/comics/1921_fact_checker.png\", \"title\": \"1921 Fact Checker\", \"day\": \"27\"}");
                add("{\"month\": \"3\", \"num\": 2130, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"Industry Nicknames\", \"transcript\": \"\", \"alt\": \"As far as \\\"being in the pocket of Big Egg\\\" goes, I think the real threat is Chansey.\", \"img\": \"https://imgs.xkcd.com/comics/industry_nicknames.png\", \"title\": \"Industry Nicknames\", \"day\": \"29\"}");
                add("{\"month\": \"4\", \"num\": 2131, \"link\": \"https://xkcd.com/2131/emojidome_bracket_round_of_128.png\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"Emojidome\", \"transcript\": \"\", \"alt\": \"Thank you to the xkcd April 1st volunteers/commentators, including @Chromakode, Kevin, @Aiiane, Patrick, Kat, Reuven, @cotrone, @bstaffin, @zigdon, schwal, Stereo, and everyone who voted!\", \"img\": \"https://imgs.xkcd.com/comics/emojidome.png\", \"title\": \"Emojidome\", \"day\": \"1\"}");
                add("{\"month\": \"4\", \"num\": 2132, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"Percentage Styles\", \"transcript\": \"\", \"alt\": \"In a tribute to classical Latin, I started pronouncing it 'per-kent.' Eventually my friends had to resort to spritzing me with a water bottle like a cat to train me out of it.\", \"img\": \"https://imgs.xkcd.com/comics/percentage_styles.png\", \"title\": \"Percentage Styles\", \"day\": \"3\"}");
                add("{\"month\": \"4\", \"num\": 2133, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"EHT Black Hole Picture\", \"transcript\": \"\", \"alt\": \"[five years later] Ok, it seems we were accidentally zoomed in slightly too far. But imagine there's a cool-looking twisted accretion disc just outside this black square!\", \"img\": \"https://imgs.xkcd.com/comics/eht_black_hole_picture.png\", \"title\": \"EHT Black Hole Picture\", \"day\": \"5\"}");
                add("{\"month\": \"4\", \"num\": 2134, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"Too Much Talking\", \"transcript\": \"\", \"alt\": \"Next time I go, I'm going to prepare a whole bunch of opinions that I'm sure are good, and make everyone sit quietly while I run through them.\", \"img\": \"https://imgs.xkcd.com/comics/too_much_talking.png\", \"title\": \"Too Much Talking\", \"day\": \"8\"}");
                add("{\"month\": \"4\", \"num\": 2135, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"M87 Black Hole Size Comparison\", \"transcript\": \"\", \"alt\": \"I think Voyager 1 would be just past the event horizon, but slightly less than halfway to the bright ring.\", \"img\": \"https://imgs.xkcd.com/comics/m87_black_hole_size_comparison.png\", \"title\": \"M87 Black Hole Size Comparison\", \"day\": \"10\"}");
                add("{\"month\": \"4\", \"num\": 2136, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"Election Commentary\", \"transcript\": \"\", \"alt\": \"This really validates Jones's strategy of getting several thousand more votes than Smith. In retrospect, that was a smart move; those votes were crucial.\", \"img\": \"https://imgs.xkcd.com/comics/election_commentary.png\", \"title\": \"Election Commentary\", \"day\": \"12\"}");
                add("{\"month\": \"4\", \"num\": 2137, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"Text Entry\", \"transcript\": \"\", \"alt\": \"I like to think that somewhere out there, there's someone whose personal quest is lobbying TV providers to add an option to switch their on-screen keyboards to Dvorak.\", \"img\": \"https://imgs.xkcd.com/comics/text_entry.png\", \"title\": \"Text Entry\", \"day\": \"15\"}");
                add("{\"month\": \"4\", \"num\": 2138, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"Wanna See the Code?\", \"transcript\": \"\", \"alt\": \"And because if you just leave it there, it's going to start contaminating things downstream even if no one touches it directly.\", \"img\": \"https://imgs.xkcd.com/comics/wanna_see_the_code.png\", \"title\": \"Wanna See the Code?\", \"day\": \"17\"}");
                add("{\"month\": \"4\", \"num\": 2139, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"Email Settings\", \"transcript\": \"\", \"alt\": \"What are all these less-than signs? What's an HREF? Look, we know you live in a fancy futuristic tech world, but not all of us have upgraded to the latest from Sun Microsystems.\", \"img\": \"https://imgs.xkcd.com/comics/email_settings.png\", \"title\": \"Email Settings\", \"day\": \"19\"}");
            }};

    public static final ArrayList<String> FAVOR_DATA =
            new ArrayList<String>(){{
                add("{\"month\": \"1\", \"num\": 18, \"link\": \"\", \"year\": \"2006\", \"news\": \"\", \"safe_title\": \"Snapple\", \"transcript\": \"{{Author's Comment: This one is entirely James' fault.}}\\n[[Two guys are standing and talking.]]\\nRight Guy: Here, take a bite of this Snapple.\\nLeft Guy: food!\\n[[Guy on the right takes a bite]]\\nRight Guy: Ow! What is this? \\n<<CLINK>>\\nLeft Guy: It's an apple infused with tin.\\n[[The two guys continue to stand as if frozen]]\\n \\n{{Author's Comment: Those of you who know your periodic table should be laughing right about now.}} \\n{{Title Text: Sn= tin}}\", \"alt\": \"Sn = tin\", \"img\": \"https://imgs.xkcd.com/comics/snapple.jpg\", \"title\": \"Snapple\", \"day\": \"1\"}");
                add("{\"month\": \"10\", \"num\": 800, \"link\": \"\", \"year\": \"2010\", \"news\": \"\", \"safe_title\": \"Beautiful Dream\", \"transcript\": \"[[A person with disheveled hair stretches their arms.  A sunburst indicating sleepiness is above their head.]]\\n<<YAWN>>\\nPerson: I just woke up [...]\\n\\n[[The person continues speaking from off panel, to a second person who's sitting at a table with a laptop and cup.  They've leaned their elbow on the chair, turning to face the first person.]]\\nPerson: From the most \\nbeautiful\\n dream.\\nSecond person: Which was?\\n\\nPerson: All the girls who read and follow \\nThe Rules\\n and all the guys who swear by the techniques in \\nThe Game\\n paired off with each other and left the rest of us alone forever.\\nSecond person: \\nMmmmmm...\\n\\n\\n{{Title text: Lucky. In MY dream, all the people who grew up loving The Giving Tree paired up with all the students who had weird dreams after reading The Metamorphosis. That one was more confusing.}}\", \"alt\": \"Lucky. In MY dream, all the people who grew up loving The Giving Tree paired up with all the students who had weird dreams after reading The Metamorphosis. That one was more confusing.\", \"img\": \"https://imgs.xkcd.com/comics/beautiful_dream.png\", \"title\": \"Beautiful Dream\", \"day\": \"1\"}");
                add("{\"month\": \"7\", \"num\": 1395, \"link\": \"\", \"year\": \"2014\", \"news\": \"\", \"safe_title\": \"Power Cord\", \"transcript\": \"[[A stick figure is sitting on a chair typing on a laptop whose cord is lying on the floor, unplugged. White Beret man approaches.]]\\n<<type type>>\\n\\n[[White Beret picks up the cord and examines it. The person in the chair continues typing.]]\\n<<type type>>\\n\\n[[White Beret puts the cord into his mouth and blows, causing the laptop to inflate, which surprises the person typing.]]\\n<<PBBBBT>>\\n<<FOOMP>>\\n\\n[[White Beret man walks away as the formerly typing person climbs up the chair to reach his now floating-away laptop.]]\\n\\n{{Title text: In this situation, gzip \\ndev\\ninside to deflate, then pipe the compressed air to \\ndev\\ninput to clean your keyboard. Avert your eyes when you do.}}\", \"alt\": \"In this situation, gzip /dev/inside to deflate, then pipe the compressed air to /dev/input to clean your keyboard. Avert your eyes when you do.\", \"img\": \"https://imgs.xkcd.com/comics/power_cord.png\", \"title\": \"Power Cord\", \"day\": \"16\"}");
                add("{\"month\": \"5\", \"num\": 1832, \"link\": \"\", \"year\": \"2017\", \"news\": \"\", \"safe_title\": \"Photo Library Management\", \"transcript\": \"\", \"alt\": \"A good lifehack is to use messy and unstable systems to organize your photos. That way, every five years or so it becomes obsolete and/or collapses, and you have to open it up and pick only your favorite pictures to salvage.\", \"img\": \"https://imgs.xkcd.com/comics/photo_library_management.png\", \"title\": \"Photo Library Management\", \"day\": \"3\"}");
                add("{\"month\": \"10\", \"num\": 325, \"link\": \"\", \"year\": \"2007\", \"news\": \"\", \"safe_title\": \"A-Minus-Minus\", \"transcript\": \"[[the hat guy is packing a bobcat into a box; a woman stands beside him.]]\\nwoman: What are you doing?\\nthe Hat Guy: Making the world a weirder place.\\nbobcat: <<mrrowlll>>\\n[[The hat guy has finished taping the package for shipping.]]\\nman: Starting with my eBay feedback page.\\n[[Bandaged person at a computer with assorted debris around the floor]]\\nscreen: comments:\\n<<bandaged person typing>> Instead of office chair package contained bobcat.\\n<<bandaged person typing>> Would not buy again.\\n{{title: You can do this one in every 30 times and still have 97% positive feedback.}}\", \"alt\": \"You can do this one in every 30 times and still have 97% positive feedback.\", \"img\": \"https://imgs.xkcd.com/comics/a-minus-minus.png\", \"title\": \"A-Minus-Minus\", \"day\": \"5\"}");
                add("{\"month\": \"11\", \"num\": 183, \"link\": \"\", \"year\": \"2006\", \"news\": \"\", \"safe_title\": \"Snacktime Rules\", \"transcript\": \"My dad was always the one who taught me about science, but looking back, I'm starting to realize how much my nerdiness was influenced by my mom.\\n[[A woman and a child are talking]]\\nChild: Mom, can I have a snack in my room before bed?\\nMom: No, Dear. You know you only get that privilege when your age is one less than a multiple of three.\\n{{alt text: I am not making this rule up.  Although my mom wants you all to know it made perfect sense at the time.}}\", \"alt\": \"I am not making this rule up.  Although my mom wants you all to know it made perfect sense at the time.\", \"img\": \"https://imgs.xkcd.com/comics/snacktime_rules.png\", \"title\": \"Snacktime Rules\", \"day\": \"13\"}");
                add("{\"month\": \"2\", \"num\": 1011, \"link\": \"\", \"year\": \"2012\", \"news\": \"\", \"safe_title\": \"Baby Names\", \"transcript\": \"[[A man sits at a desk, thinking with his hand on his chin, his other hand holding a pen over a piece of paper. A woman stands behind him, looking over his shoulder, also with her hand on her chin.]] \\n((Above the drawing is the list they are writing, in handwriting.))\\n\\nNames for daughter\\n1. Ponzi\\n2. Eeemily\\n3. Fire Fire\\n4. Chipotla\\n5. Astamouthe\\n6. Eggsperm\\n7. [sound of record scratch]\\n8. Parsley\\n9. Hot'n'Juicy Ann\\n10. Ovary\\n11. Friendly\\n12. Sean (pronounced \\\"seen\\\")\\n13. Joyst\\n\\n{{Title text: I've been trying for a couple years now but I haven't been able to come up with a name dumber than 'Renesmee'.}}\", \"alt\": \"I've been trying for a couple years now but I haven't been able to come up with a name dumber than 'Renesmee'.\", \"img\": \"https://imgs.xkcd.com/comics/baby_names.png\", \"title\": \"Baby Names\", \"day\": \"1\"}");
                add("{\"month\": \"3\", \"num\": 1032, \"link\": \"\", \"year\": \"2012\", \"news\": \"\", \"safe_title\": \"Networking\", \"transcript\": \"[[A man approaches white beret man at a party and they extend arms to shake hands. WBM is holding a metal briefcase. There is a waitress in the background, carrying a tray with a wine glass on it.]]\\nMan: I'm Connr Clark, CTO at Eusocial Median Ventures.\\nWhite Beret: I'm a business professional! Earlier I photocopied a burrito!\\n\\n[[The man man hands WBM a business card. WBM takes it and hands the man another business card. WBM has put his suitcase on the floor.]]\\nMan: You should check us out! Here's my card.\\nWhite Beret: Here's mine! -- Networking!\\n\\n[[The man takes a closer look at the card, and WBM holds up his case.]]\\nMan: ...This just says \\\"This is my business card!\\\" \\nWhite Beret: Do you like it? I have more in my handlebox.\\n\\n[[WBM puts his case on a table and opens it to reveal it is full of cash. The man looks on in shock.]]\\nMan: Uh, that's ok, I think I'll--\\nWhite Beret: Here, have ten of them!\\nMan: --holy shit that thing is full of \\ncash!\\n\\n\\n[[The man raises his arms in excitement. WBM turns to face him and chews on something.]]\\nMan: Where did you \\nget\\n that?\\nWhite Beret: I am a business grown-up who makes business profits!\\nMan: That's like a quarter of a million dollars!\\nWhite Beret: Yay! Business is fun! -- Do you have more of your cards? They're \\ndelicious!\\n\\n\\n{{Title text: Our company is agile and lean with a focus on the long tail. Ok, our company is actually a polecat I found in my backyard.}}\", \"alt\": \"Our company is agile and lean with a focus on the long tail. Ok, our company is actually a polecat I found in my backyard.\", \"img\": \"https://imgs.xkcd.com/comics/networking.png\", \"title\": \"Networking\", \"day\": \"21\"}");
                add("{\"month\": \"5\", \"num\": 577, \"link\": \"\", \"year\": \"2009\", \"news\": \"For this week, xkcd will update once a day.\", \"safe_title\": \"The Race: Part 1\", \"transcript\": \"Huh, cool. Nathan Fillion (Mal from Firefly) has an electric skateboard. Just like you!\\nDid you hear that? Nathan-\\nI heard. Gimme the computer. I need to book a flight.\\nTo be continued...\", \"alt\": \"Great, and you JUST finished paying off the settlement over the Wayne Coyne hamster ball incident.\", \"img\": \"https://imgs.xkcd.com/comics/the_race_part_1.png\", \"title\": \"The Race: Part 1\", \"day\": \"4\"}");
                add("{\"month\": \"12\", \"num\": 1459, \"link\": \"\", \"year\": \"2014\", \"news\": \"\", \"safe_title\": \"Documents\", \"transcript\": \"[[White Hat Guy sits at a desk and types at a computer. Stick Guy looks over his shoulder. A balloon shows a list of documents on the screen:\\nUntitled 138.docx\\nUntitled 241.doc\\nUntitled 138 copy.docx\\nUntitled 138 copy2.docx\\nUntitled 139.docx\\nUntitled 40 MOM ADDRESS.jpg\\nUntiled 242.doc\\nUntitled 243.doc\\nUntitled 243 IMPORTANT.doc\\nUntitled41.doc\\n..and so on.]]\\nSG: \\nOH MY GOD.\\n\\nProtip: never look in someone else's documents folder.\\n{{Title text: Copy of Copy of Copy of Copy of Copy of Copy of Copy of Copy of Copy of Copy of Copy of Copy of Copy of Copy of Copy of Copy of Copy of Copy of Copy of Copy of Copy of Copy of Copy of Copy of Copy of Copy of Copy of Copy of Copy of Copy of Copy of Copy of Copy of Untitled.doc}}\", \"alt\": \"Copy of Copy of Copy of Copy of Copy of Copy of Copy of Copy of Copy of Copy of Copy of Copy of Copy of Copy of Copy of Copy of Copy of Copy of Copy of Copy of Copy of Copy of Copy of Copy of Copy of Copy of Copy of Copy of Copy of Copy of Copy of Copy of Copy of Untitled.doc\", \"img\": \"https://imgs.xkcd.com/comics/documents.png\", \"title\": \"Documents\", \"day\": \"12\"}");
                add("{\"month\": \"8\", \"num\": 1877, \"link\": \"\", \"year\": \"2017\", \"news\": \"\", \"safe_title\": \"Eclipse Science\", \"transcript\": \"\", \"alt\": \"I was thinking of observing stars to verify Einstein's theory of relativity again, but I gotta say, that thing is looking pretty solid at this point.\", \"img\": \"https://imgs.xkcd.com/comics/eclipse_science.png\", \"title\": \"Eclipse Science\", \"day\": \"16\"}");
                add("{\"month\": \"3\", \"num\": 241, \"link\": \"\", \"year\": \"2007\", \"news\": \"\", \"safe_title\": \"Battle Room\", \"transcript\": \"[[A scene is depicted from the Battle Room of the novel Ender's Game by Orson Scott Card.  The men are floating in a room with random cubes.]]\\nDink: Sorry, Ender - seems like there were some system crashes.  The battle's gotta be cut short.\\nEnder: The lasers still work.\\nDink: Yeah, but the enemy's gate is down.\\n{{Title Text: Bean actually sabotaged it just to give Dink the excuse to make that joke.}}\", \"alt\": \"Bean actually sabotaged it just to give Dink the excuse to make that joke.\", \"img\": \"https://imgs.xkcd.com/comics/battle_room.png\", \"title\": \"Battle Room\", \"day\": \"28\"}");
                add("{\"month\": \"12\", \"num\": 513, \"link\": \"\", \"year\": \"2008\", \"news\": \"\", \"safe_title\": \"Friends\", \"transcript\": \"[[A boy is talking to a girl.]]\\nBoy: I have a crush on you.\\n[[Boy is shown alone.]]\\nBoy: I could ask you out, and move on with my life if you said no.\\nBoy: Or, WE COULD BE FRIENDS!\\nBoy: See, I don't want to consider that you might not be attracted to me. I'm scared of rejection, so I've decided relationships should grow smoothly out of friendships.\\n[[Girl is shown sitting at her computer.]]\\nBoy: When you have problems, I'll be there for you, night after night.\\nBoy: Selflessly.\\nComputer (Instant message from boy): *hug*\\n[[Girl is shown slamming door and walkng to boy to get a hug.]]\\nBoy: I'll tear down the jerks you date, and wait for you to realize how good I am for you. That only I will ever understand you.\\n<<SLAM>>\\nGirl: <<Sniff>>\\nBoy: There there\\n[[Boy is shown alone again.]]\\nBoy: You don't want to hurt my feelings, and I won't ever force the issue. I'll tell myself it's because I \\\"Value our friendship.\\\"\\nBoy: Bit by bit, I'll make you depend on me.\\n[[Boy and girl are shown sitting on a rock in a park, reading a book together.]]\\nBoy: You'll think about how long it would take to build this kind of connection again.\\n[[Boy and girl are shown sitting on a couch drinking, getting closer, and kissing.]]\\nBoy: And in a moment of weakness\\nBoy: and loneliness\\nBoy: you'll give in.\\n[[Girl is shown sitting at the computer with boy behind her facing the other way washing dishes]]\\nBoy: It'll feel comfortable and natural. You'll quietly revise your definition of love and try to be happy. And sometimes you will be.\\n[[Girl is shown siting at the computer.]]\\nBoy: Only the wistfulness in your gaze and the tiny pause before you say \\\"I love you\\\" will hint that this wasn't the ending you'd hoped for.\\nBoy: Sound good?\\n[[Girl is holding hands with another boy, talking to boy.]]\\nGirl: ...I'm going to date this jerk.\\nBoy: But he doesn't respect you!\\n{{title text: Friends with detriments.}}\", \"alt\": \"Friends with detriments.\", \"img\": \"https://imgs.xkcd.com/comics/friends.png\", \"title\": \"Friends\", \"day\": \"5\"}");
                add("{\"month\": \"8\", \"num\": 1559, \"link\": \"\", \"year\": \"2015\", \"news\": \"\", \"safe_title\": \"Driving\", \"transcript\": \"[[black hat guy walks up to a figure carrying a large, heavy rock]]\\nBlack hat guy: Would you guess this weighs as much as a small adult?\\nFigure: What? Uh, probably.\\n\\n[[black hat guy walks off panel with the panel]]\\nblack hat guy: great!\\n\\n[[offscreen]]\\n<<thump>>\\nCar: Please fasten your seat belt.\\n<<click>>\\nblack hate guy: Take me to Anchorage, Alaska.\\ncar: navigating.\\n<<slam>>\\n<<vrrrrrrrrr>>\\n\\n[[Black hat guy returns to frame]]\\nblack hat guy: I love self driving cars.\\nfigure: ...whose car was that?\\nblack hat guy: dunno, but they shouldn't have left it running.\\n\\n{{Title text: Sadly, it probably won't even have enough gas to make it to the first border crossing.}}\", \"alt\": \"Sadly, it probably won't even have enough gas to make it to the first border crossing.\", \"img\": \"https://imgs.xkcd.com/comics/driving.png\", \"title\": \"Driving\", \"day\": \"3\"}");
                add("{\"month\": \"7\", \"num\": 927, \"link\": \"\", \"year\": \"2011\", \"news\": \"\", \"safe_title\": \"Standards\", \"transcript\": \"HOW STANDARDS PROLIFERATE\\n(See: A\\nC chargers, character encodings, instant messaging, etc.)\\n\\nSITUATION:\\nThere are 14 competing standards.\\n\\nGeek: 14?! Ridiculous! We need to develop one universal standard that covers everyone's use cases.\\nFellow Geek: Yeah!\\n\\nSoon:\\nSITUATION:\\nThere are 15 competing standards.\\n\\n{{Title text: Fortunately, the charging one has been solved now that we've all standardized on mini-USB. Or is it micro-USB? Shit.}}\", \"alt\": \"Fortunately, the charging one has been solved now that we've all standardized on mini-USB. Or is it micro-USB? Shit.\", \"img\": \"https://imgs.xkcd.com/comics/standards.png\", \"title\": \"Standards\", \"day\": \"20\"}");
                add("{\"month\": \"1\", \"num\": 530, \"link\": \"\", \"year\": \"2009\", \"news\": \"\", \"safe_title\": \"I'm An Idiot\", \"transcript\": \"[[Ponytailed stick figure approaches stick figure, who is sitting on porch steps, laptop in lap and backpack open]]\\nPonytailed stick figure: Should  I ask?\\nStick figure: I'm locked out, and I'm trying to get my roommate to let me in.\\n[[unplugged cell phone on table]]\\nStick figure: First I tried her cell phone, but it's off.\\n[[Stick figure sitting on steps, laptop in lap and gesturing]]\\nStick figure: Then I tried IRC, but she's not online.\\n[[Stick figure standing in front of house and looking up at window]]\\nStick figure: I couldn't find anything to throw at her window,\\n[[living room with couch\\neasy chair and computer set up]]\\nStick figure: so I SSH'd into the Mac Mini in the living room and got the speech synth to yell at her for me.\\nComputer: Hey I'm locked out downstairs\\n[[Roommate sitting at table with laptop open]]\\nStick figure: But I think I left the volume way down, so I'm reading the OS X docs to learn to set the volume via command line.\\n[[Ponytailed stick figure facing stick figure, who is still sitting on the porch with his laptop.]]\\nPonytailed stick figure: Ah.\\nPonytailed stick figure: I take it the doorbell doesn't work?\\n[[Ponytailed stick figure characters remain in place, Stick figure tilts head back slightly, as if staring in realization]]\", \"alt\": \"Sadly, this is a true story.  At least I learned about the OS X 'say' command.\", \"img\": \"https://imgs.xkcd.com/comics/im_an_idiot.png\", \"title\": \"I'm An Idiot\", \"day\": \"14\"}");
                add("{\"month\": \"1\", \"num\": 1, \"link\": \"\", \"year\": \"2006\", \"news\": \"\", \"safe_title\": \"Barrel - Part 1\", \"transcript\": \"[[A boy sits in a barrel which is floating in an ocean.]]\\nBoy: I wonder where I'll float next?\\n[[The barrel drifts into the distance. Nothing else can be seen.]]\\n{{Alt: Don't we all.}}\", \"alt\": \"Don't we all.\", \"img\": \"https://imgs.xkcd.com/comics/barrel_cropped_(1).jpg\", \"title\": \"Barrel - Part 1\", \"day\": \"1\"}");
                add("{\"month\": \"1\", \"num\": 2, \"link\": \"\", \"year\": \"2006\", \"news\": \"\", \"safe_title\": \"Petit Trees (sketch)\", \"transcript\": \"[[Two trees are growing on opposite sides of a sphere.]]\\n{{Alt-title: 'Petit' being a reference to Le Petit Prince, which I only thought about halfway through the sketch}}\", \"alt\": \"'Petit' being a reference to Le Petit Prince, which I only thought about halfway through the sketch\", \"img\": \"https://imgs.xkcd.com/comics/tree_cropped_(1).jpg\", \"title\": \"Petit Trees (sketch)\", \"day\": \"1\"}");
                add("{\"month\": \"1\", \"num\": 22, \"link\": \"\", \"year\": \"2006\", \"news\": \"\", \"safe_title\": \"Barrel - Part 3\", \"transcript\": \"[[Large vortex, spinning water covers the whole panel. A boy in a floating barrel is near the edge, apparently about to be sucked in.]]\\nBoy: Wow!\\n{{alt text: A whirlpool!}}\", \"alt\": \"A whirlpool!\", \"img\": \"https://imgs.xkcd.com/comics/barrel_whirlpool.jpg\", \"title\": \"Barrel - Part 3\", \"day\": \"1\"}");
                add("{\"month\": \"6\", \"num\": 121, \"link\": \"\", \"year\": \"2006\", \"news\": \"\", \"safe_title\": \"Balloon\", \"transcript\": \"I watched the scene in the restaurant for a full fifteen minutes hoping this would happen:\\n[[Figure holding balloon;  Balloon gets caught in ceiling fan;  Figure holds on and is pulled up]]\\n{{alt: So I'm a bad person.}}\", \"alt\": \"So I'm a bad person.\", \"img\": \"https://imgs.xkcd.com/comics/balloon.png\", \"title\": \"Balloon\", \"day\": \"28\"}");
                add("{\"month\": \"2\", \"num\": 222, \"link\": \"\", \"year\": \"2007\", \"news\": \"\", \"safe_title\": \"Small Talk\", \"transcript\": \"Sometimes I forget how to do small talk.\\n[[Two people are talking to each other]]\\nFirst person: Hey!\\nSecond person: Hey, man!\\nFirst person: What's up? How've you been?\\nSecond person: Well...\\n[[Nothing happens]]\\n[[Nothing happens]]\\n[[Nothing happens]]\\nFirst person: Uh, you okay?\\nSecond person: Yeah! It's just an interesting question. I'm trying to decide what best sums up my -\\nFirst person: <<SNAP>> Hey, conversation.\\nSecond person: Oh, right. I'm fine. You?\\n{{title text: But surely I owe you an accurate answer!}}\", \"alt\": \"But surely I owe you an accurate answer!\", \"img\": \"https://imgs.xkcd.com/comics/small_talk.png\", \"title\": \"Small Talk\", \"day\": \"12\"}");
                add("{\"month\": \"11\", \"num\": 666, \"link\": \"\", \"year\": \"2009\", \"news\": \"\", \"safe_title\": \"Silent Hammer\", \"transcript\": \"[[Hat guy is hammering something on a table.]]\\nGuy: What--\\nHat Guy: Silent hammer. I've made a set of silent tools.\\nGuy: Why?\\nHammer: <<whoosh whoosh whoosh>>\\n\\nHat Guy: Stealth carpentry. Breaking into a house at night and moving windows, adjusting walls, etc.\\n[[He takes his silent hammer over to a tool bench with other things on it. Two boxes underneath are labeled \\\"Drills\\\" and \\\"Non-Drills.\\\"]]\\n\\nHat Guy, narrating: After a week or so of questioning his own sanity, the owner will stay up to watch the house at night. I'll make scratching noises in the walls, pipe in knockout gas, move him up to his bed, and never bother him again.\\n[[The events he's describing are shown in two mini-panels below.]]\\n\\nGuy, off-panel: Nice prank, I guess, but what's the point?\\nHat Guy: Check out the owner's card, on the table.\\nGuy, off-panel: Chair of the American Skeptics Society? Oh, god.\\nHat guy: Yeah, this doesn't end well for him.\\n\\n{{Title text: I bet he'll keep quiet for a couple weeks and then-- wait, did you nail a piece of scrap wood to my antique table a moment ago?}}\", \"alt\": \"I bet he'll keep quiet for a couple weeks and then-- wait, did you nail a piece of scrap wood to my antique table a moment ago?\", \"img\": \"https://imgs.xkcd.com/comics/silent_hammer.png\", \"title\": \"Silent Hammer\", \"day\": \"23\"}");
                add("{\"month\": \"6\", \"num\": 1221, \"link\": \"\", \"year\": \"2013\", \"news\": \"\", \"safe_title\": \"Nomenclature\", \"transcript\": \"[[Mrs. Whatsit is talking to Abbott and Costello.]]\\nMrs. Whatsit: You're both confused.\\nMrs. Whatsit: He's just \\\"The Doctor\\\".\\n\\n{{Title text: [shouted, from the field] 'Aunt Beast hit a pop fly to second! Dive for it, Mrs Whatsit!'}}\", \"alt\": \"[shouted, from the field] 'Aunt Beast hit a pop fly to second! Dive for it, Mrs Whatsit!'\", \"img\": \"https://imgs.xkcd.com/comics/nomenclature.png\", \"title\": \"Nomenclature\", \"day\": \"5\"}");
                add("{\"month\": \"3\", \"num\": 2122, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"Size Venn Diagram\", \"transcript\": \"\", \"alt\": \"Terms I'm going to start using: The Large Dipper, great potatoes, the Big Hadron Collider, and Large Orphan Annie.\", \"img\": \"https://imgs.xkcd.com/comics/size_venn_diagram.png\", \"title\": \"Size Venn Diagram\", \"day\": \"11\"}");
                add("{\"month\": \"3\", \"num\": 2123, \"link\": \"\", \"year\": \"2019\", \"news\": \"\", \"safe_title\": \"Meta Collecting\", \"transcript\": \"\", \"alt\": \"I'm trying to get the page locked because some jerk keeps adding \\\"Yachts\\\".\", \"img\": \"https://imgs.xkcd.com/comics/meta_collecting.png\", \"title\": \"Meta Collecting\", \"day\": \"13\"}");

            }};

}
